/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CounselRouteImport } from './routes/counsel'
import { Route as DrillRouteImport } from './routes/drill'
import { Route as MirrorRouteImport } from './routes/mirror'
import { Route as PathRouteImport } from './routes/path'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as CodexIndexRouteImport } from './routes/codex.index'
import { Route as CodexSlugRouteImport } from './routes/codex.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CounselRoute = CounselRouteImport.update({
  id: '/counsel',
  path: '/counsel',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillRoute = DrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => rootRouteImport,
} as any)
const MirrorRoute = MirrorRouteImport.update({
  id: '/mirror',
  path: '/mirror',
  getParentRoute: () => rootRouteImport,
} as any)
const PathRoute = PathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexIndexRoute = CodexIndexRouteImport.update({
  id: '/codex/',
  path: '/codex/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexSlugRoute = CodexSlugRouteImport.update({
  id: '/codex/$slug',
  path: '/codex/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/counsel': typeof CounselRoute
  '/drill': typeof DrillRoute
  '/mirror': typeof MirrorRoute
  '/path': typeof PathRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/chat': typeof ApiChatRoute
  '/codex/$slug': typeof CodexSlugRoute
  '/codex/': typeof CodexIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/counsel': typeof CounselRoute
  '/drill': typeof DrillRoute
  '/mirror': typeof MirrorRoute
  '/path': typeof PathRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/chat': typeof ApiChatRoute
  '/codex/$slug': typeof CodexSlugRoute
  '/codex': typeof CodexIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/counsel': typeof CounselRoute
  '/drill': typeof DrillRoute
  '/mirror': typeof MirrorRoute
  '/path': typeof PathRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/chat': typeof ApiChatRoute
  '/codex/$slug': typeof CodexSlugRoute
  '/codex/': typeof CodexIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/counsel'
    | '/drill'
    | '/mirror'
    | '/path'
    | '/admin'
    | '/api/chat'
    | '/codex/$slug'
    | '/codex/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/counsel'
    | '/drill'
    | '/mirror'
    | '/path'
    | '/admin'
    | '/api/chat'
    | '/codex/$slug'
    | '/codex'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/counsel'
    | '/drill'
    | '/mirror'
    | '/path'
    | '/_authenticated/admin'
    | '/api/chat'
    | '/codex/$slug'
    | '/codex/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CounselRoute: typeof CounselRoute
  DrillRoute: typeof DrillRoute
  MirrorRoute: typeof MirrorRoute
  PathRoute: typeof PathRoute
  ApiChatRoute: typeof ApiChatRoute
  CodexSlugRoute: typeof CodexSlugRoute
  CodexIndexRoute: typeof CodexIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsel': {
      id: '/counsel'
      path: '/counsel'
      fullPath: '/counsel'
      preLoaderRoute: typeof CounselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill': {
      id: '/drill'
      path: '/drill'
      fullPath: '/drill'
      preLoaderRoute: typeof DrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mirror': {
      id: '/mirror'
      path: '/mirror'
      fullPath: '/mirror'
      preLoaderRoute: typeof MirrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path': {
      id: '/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof PathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex/': {
      id: '/codex/'
      path: '/codex'
      fullPath: '/codex/'
      preLoaderRoute: typeof CodexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex/$slug': {
      id: '/codex/$slug'
      path: '/codex/$slug'
      fullPath: '/codex/$slug'
      preLoaderRoute: typeof CodexSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CounselRoute: CounselRoute,
  DrillRoute: DrillRoute,
  MirrorRoute: MirrorRoute,
  PathRoute: PathRoute,
  ApiChatRoute: ApiChatRoute,
  CodexSlugRoute: CodexSlugRoute,
  CodexIndexRoute: CodexIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
